-- Patch 11.2.2 · Friends System
-- Canonical undirected friendship pair + reusable social notification inbox.

create table if not exists public.friendships (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  requested_by uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending','accepted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  accepted_at timestamptz,
  constraint friendships_distinct_users check (user_a <> user_b),
  constraint friendships_requested_by_pair check (requested_by in (user_a, user_b)),
  constraint friendships_canonical_pair check (user_a::text < user_b::text),
  constraint friendships_unique_pair unique (user_a, user_b)
);

create index if not exists friendships_user_a_status_idx
  on public.friendships(user_a, status, updated_at desc);

create index if not exists friendships_user_b_status_idx
  on public.friendships(user_b, status, updated_at desc);

alter table public.friendships enable row level security;

create table if not exists public.social_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  type text not null
    check (type in (
      'friend_request',
      'friend_accepted',
      'watch_party_invite',
      'ranking_overtaken',
      'ranking_entered_top10'
    )),
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists social_notifications_user_created_idx
  on public.social_notifications(user_id, created_at desc);

create index if not exists social_notifications_user_unread_idx
  on public.social_notifications(user_id, created_at desc)
  where read_at is null;

alter table public.social_notifications enable row level security;
