-- AnimeBox Patch 7 — Watch Together v2 / Public Rooms
create table if not exists public.watch_party_rooms (
  id text primary key,
  join_secret text not null,
  host_user_id uuid not null references auth.users(id) on delete cascade,
  anime_id integer,
  anime_slug text not null,
  anime_title text not null,
  cover_url text,
  episode integer not null check (episode >= 1 and episode <= 100000),
  visibility text not null default 'unlisted' check (visibility in ('private','unlisted','public')),
  status text not null default 'waiting' check (status in ('waiting','watching','paused','voting','ended')),
  language text not null default 'ru',
  participant_count integer not null default 1 check (participant_count between 0 and 8),
  max_participants integer not null default 8 check (max_participants between 2 and 8),
  room_code text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_heartbeat_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '8 hours'),
  ended_at timestamptz,
  constraint watch_party_room_id_format check (id ~ '^[a-f0-9]{24}$'),
  constraint watch_party_join_secret_format check (join_secret ~ '^[a-f0-9]{32}$')
);

create index if not exists watch_party_rooms_public_live_idx
  on public.watch_party_rooms (visibility, status, last_heartbeat_at desc)
  where visibility = 'public' and status <> 'ended';

create index if not exists watch_party_rooms_host_idx
  on public.watch_party_rooms (host_user_id, updated_at desc);

create table if not exists public.watch_party_room_reports (
  id bigint generated by default as identity primary key,
  room_id text not null references public.watch_party_rooms(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  target_user_id uuid references auth.users(id) on delete set null,
  reason text not null check (char_length(reason) between 3 and 300),
  created_at timestamptz not null default now()
);

create index if not exists watch_party_room_reports_room_idx
  on public.watch_party_room_reports (room_id, created_at desc);

alter table public.watch_party_rooms enable row level security;
alter table public.watch_party_room_reports enable row level security;

-- No direct client policies on purpose.
-- Room directory/mutations go through authenticated server routes using service_role.
