-- AnimeBox Patch 8 · Watch Together Public Rooms v2
-- Reproducible schema for the public room registry and moderation reports.
-- Browser clients do not access these tables directly; Next.js server routes
-- use the service role after validating the authenticated user.

create table if not exists public.watch_party_rooms (
  id text primary key
    constraint watch_party_room_id_format check (id ~ '^[a-f0-9]{24}$'),
  join_secret text not null
    constraint watch_party_join_secret_format check (join_secret ~ '^[a-f0-9]{32}$'),
  host_user_id uuid not null references auth.users(id) on delete cascade,
  anime_id integer,
  anime_slug text not null,
  anime_title text not null,
  cover_url text,
  episode integer not null check (episode between 1 and 100000),
  visibility text not null default 'unlisted'
    check (visibility in ('private', 'unlisted', 'public')),
  status text not null default 'waiting'
    check (status in ('waiting', 'watching', 'paused', 'voting', 'ended')),
  language text not null default 'ru',
  participant_count integer not null default 1
    check (participant_count between 0 and 8),
  max_participants integer not null default 8
    check (max_participants between 2 and 8),
  room_code text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_heartbeat_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '8 hours'),
  ended_at timestamptz
);

create table if not exists public.watch_party_room_reports (
  id bigint generated by default as identity primary key,
  room_id text not null references public.watch_party_rooms(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  target_user_id uuid references auth.users(id) on delete set null,
  reason text not null check (char_length(reason) between 3 and 300),
  created_at timestamptz not null default now()
);

create index if not exists watch_party_rooms_host_idx
  on public.watch_party_rooms (host_user_id, updated_at desc);

create index if not exists watch_party_rooms_public_live_idx
  on public.watch_party_rooms (visibility, status, last_heartbeat_at desc)
  where visibility = 'public' and status <> 'ended';

create index if not exists watch_party_room_reports_room_idx
  on public.watch_party_room_reports (room_id, created_at desc);

create index if not exists watch_party_room_reports_reporter_idx
  on public.watch_party_room_reports (reporter_user_id, room_id, created_at desc);

create index if not exists watch_party_room_reports_target_idx
  on public.watch_party_room_reports (target_user_id, created_at desc)
  where target_user_id is not null;

alter table public.watch_party_rooms enable row level security;
alter table public.watch_party_room_reports enable row level security;

-- These tables are intentionally server-only. Keep browser roles unable to
-- reach them even if project Data API defaults change.
revoke all on table public.watch_party_rooms from anon, authenticated;
revoke all on table public.watch_party_room_reports from anon, authenticated;

grant select, insert, update, delete on table public.watch_party_rooms to service_role;
grant select, insert, update, delete on table public.watch_party_room_reports to service_role;

do $$
begin
  if to_regclass('public.watch_party_room_reports_id_seq') is not null then
    revoke all on sequence public.watch_party_room_reports_id_seq from anon, authenticated;
    grant usage, select on sequence public.watch_party_room_reports_id_seq to service_role;
  end if;
end
$$;
