-- AnimeBox Sponsor Reliability v1
-- Run once in Supabase before deploying the Stage 2.5.1 code.

alter table public.star_payments
  add column if not exists status text not null default 'confirmed',
  add column if not exists telegram_verified_at timestamptz,
  add column if not exists refunded_at timestamptz,
  add column if not exists refund_reason text,
  add column if not exists reconciliation_status text not null default 'pending',
  add column if not exists reconciliation_error text,
  add column if not exists admin_note text,
  add column if not exists updated_at timestamptz not null default now();

do $$ begin
  alter table public.star_payments add constraint star_payments_status_check
    check (status in ('confirmed','refunded','disputed','reconciliation_error'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.star_payments add constraint star_payments_reconciliation_status_check
    check (reconciliation_status in ('pending','verified','not_found','mismatch','refunded','error'));
exception when duplicate_object then null; end $$;

create index if not exists star_payments_status_idx
  on public.star_payments(status, created_at desc);
create index if not exists star_payments_reconciliation_idx
  on public.star_payments(reconciliation_status, created_at desc);

create table if not exists public.star_payment_events (
  id bigint generated by default as identity primary key,
  payment_id uuid references public.star_payments(id) on delete cascade,
  event_type text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint star_payment_events_type_check check (event_type in (
    'payment_received','telegram_verified','payment_recovered','reconciliation_mismatch',
    'reconciliation_not_found','reconciliation_failed','refund_requested','refund_completed',
    'refund_failed','admin_note_updated'
  ))
);

create index if not exists star_payment_events_payment_idx
  on public.star_payment_events(payment_id, created_at desc);

alter table public.star_payment_events enable row level security;
-- No public policies: only service-role/admin server access.

-- Sponsor totals must count only confirmed, non-refunded payments.
create or replace function public.update_sponsor_account_v2()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  k text;
begin
  if tg_op <> 'INSERT' and old.status = 'confirmed' then
    k := case when old.user_id is not null then 'u:' || old.user_id::text else 't:' || old.telegram_id::text end;
    update public.sponsor_accounts
       set total_stars = greatest(0, total_stars - old.amount),
           payment_count = greatest(0, payment_count - 1),
           updated_at = now()
     where account_key = k;
  end if;

  if tg_op <> 'DELETE' and new.status = 'confirmed' then
    k := case when new.user_id is not null then 'u:' || new.user_id::text else 't:' || new.telegram_id::text end;
    insert into public.sponsor_accounts(account_key,user_id,telegram_id,total_stars,payment_count)
      values(k,new.user_id,case when new.user_id is null then new.telegram_id else null end,new.amount,1)
    on conflict(account_key) do update
      set total_stars = public.sponsor_accounts.total_stars + excluded.total_stars,
          payment_count = public.sponsor_accounts.payment_count + 1,
          updated_at = now();
  end if;

  return null;
end
$$;

-- Keep updated_at current without relying on the application.
create or replace function public.touch_star_payment_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end
$$;

drop trigger if exists star_payments_touch_updated_at on public.star_payments;
create trigger star_payments_touch_updated_at
before update on public.star_payments
for each row execute function public.touch_star_payment_updated_at();
