-- AnimeBox Unified Payments v1
-- Additive migration: existing Telegram Stars / sponsor tables remain untouched.

create table if not exists public.payment_products (
  code text primary key,
  name text not null,
  product_type text not null check (product_type in ('support', 'donation', 'subscription', 'gift', 'admin')),
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid null references auth.users(id) on delete set null,
  provider text not null check (char_length(provider) between 2 and 64),
  product_code text not null references public.payment_products(code),
  external_id text not null check (char_length(external_id) between 1 and 255),
  external_user_id text null,
  status text not null check (status in ('pending', 'paid', 'failed', 'cancelled', 'partially_refunded', 'refunded')),
  amount numeric(18,4) not null check (amount >= 0),
  currency text not null check (char_length(currency) between 2 and 12),
  provider_status text null,
  provider_created_at timestamptz null,
  paid_at timestamptz null,
  refunded_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, external_id)
);

create index if not exists payment_transactions_user_created_idx
  on public.payment_transactions (user_id, created_at desc);
create index if not exists payment_transactions_provider_created_idx
  on public.payment_transactions (provider, created_at desc);
create index if not exists payment_transactions_status_created_idx
  on public.payment_transactions (status, created_at desc);
create index if not exists payment_transactions_product_code_idx
  on public.payment_transactions (product_code);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  transaction_id uuid not null references public.payment_transactions(id) on delete cascade,
  event_type text not null check (char_length(event_type) between 3 and 100),
  actor_user_id uuid null references auth.users(id) on delete set null,
  provider_event_id text null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists payment_events_transaction_created_idx
  on public.payment_events (transaction_id, created_at desc);
create index if not exists payment_events_actor_user_idx
  on public.payment_events (actor_user_id)
  where actor_user_id is not null;
create unique index if not exists payment_events_provider_event_unique_idx
  on public.payment_events (transaction_id, provider_event_id)
  where provider_event_id is not null;

create table if not exists public.payment_provider_sync_state (
  provider text primary key,
  cursor text null,
  last_synced_at timestamptz null,
  last_error text null,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_entitlements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  entitlement text not null check (char_length(entitlement) between 2 and 100),
  source text not null check (char_length(source) between 2 and 64),
  source_id text not null default '',
  active boolean not null default true,
  starts_at timestamptz not null default now(),
  expires_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, entitlement, source, source_id),
  check (expires_at is null or expires_at > starts_at)
);

create index if not exists user_entitlements_active_idx
  on public.user_entitlements (user_id, entitlement, active, expires_at);

alter table public.payment_products enable row level security;
alter table public.payment_transactions enable row level security;
alter table public.payment_events enable row level security;
alter table public.payment_provider_sync_state enable row level security;
alter table public.user_entitlements enable row level security;

-- These tables intentionally have no client policies in v1.
-- All reads/writes go through server-only routes using the service role.

insert into public.payment_products (code, name, product_type, active, metadata)
values
  ('sponsor_support', 'Поддержка AnimeBox', 'support', true, '{"source":"animebox"}'::jsonb),
  ('donation_once', 'Разовый донат', 'donation', true, '{"source":"animebox"}'::jsonb),
  ('premium_monthly', 'AnimeBox Premium · месяц', 'subscription', false, '{"planned":true}'::jsonb),
  ('premium_yearly', 'AnimeBox Premium · год', 'subscription', false, '{"planned":true}'::jsonb),
  ('gift_premium_month', 'AnimeBox Premium · подарок', 'gift', false, '{"planned":true}'::jsonb)
on conflict (code) do update
set
  name = excluded.name,
  product_type = excluded.product_type,
  metadata = excluded.metadata,
  updated_at = now();

-- Import existing Telegram Stars into the unified ledger without changing
-- the legacy sponsor system. The unique(provider, external_id) key makes
-- this migration and future dual-writes idempotent.
insert into public.payment_transactions (
  user_id,
  provider,
  product_code,
  external_id,
  external_user_id,
  status,
  amount,
  currency,
  provider_status,
  provider_created_at,
  paid_at,
  refunded_at,
  metadata,
  created_at,
  updated_at
)
select
  sp.user_id,
  'telegram_stars',
  'sponsor_support',
  sp.telegram_payment_charge_id,
  sp.telegram_id::text,
  case
    when sp.status = 'refunded' then 'refunded'
    when sp.status = 'confirmed' then 'paid'
    when sp.status in ('disputed', 'reconciliation_error') then 'failed'
    else 'pending'
  end,
  sp.amount::numeric,
  sp.currency,
  sp.status,
  sp.created_at,
  case when sp.status in ('confirmed', 'refunded') then sp.created_at else null end,
  sp.refunded_at,
  jsonb_build_object(
    'legacy_star_payment_id', sp.id,
    'telegram_id', sp.telegram_id,
    'reconciliation_status', sp.reconciliation_status
  ),
  sp.created_at,
  coalesce(sp.updated_at, sp.created_at)
from public.star_payments sp
on conflict (provider, external_id) do nothing;

insert into public.payment_events (transaction_id, event_type, details, created_at)
select
  pt.id,
  'payment.imported',
  jsonb_build_object('source', 'star_payments'),
  pt.created_at
from public.payment_transactions pt
where pt.provider = 'telegram_stars'
  and not exists (
    select 1
    from public.payment_events pe
    where pe.transaction_id = pt.id
      and pe.event_type = 'payment.imported'
  );
