-- AnimeBox Patch 19.0 — Episode Journey / Jutsu-style story achievements.
-- Events are generated offline and approved before they become visible to viewers.
-- Runtime unlocks are server-verified against trusted watch coverage, never raw client time.

create table if not exists public.episode_events (
  id uuid primary key default gen_random_uuid(),
  anime_id bigint not null,
  episode_number integer not null check (episode_number > 0),
  event_key text not null,
  kind text not null check (kind in (
    'character_intro',
    'battle',
    'tension',
    'reveal',
    'secret',
    'death',
    'finale',
    'arc_complete',
    'episode_milestone'
  )),
  title text not null,
  description text not null default '',
  at_ms integer not null check (at_ms >= 0 and at_ms <= 28800000),
  rarity text not null default 'common' check (rarity in ('common','uncommon','rare','epic','legendary')),
  image_url text,
  confidence numeric(4,3) not null default 1 check (confidence >= 0 and confidence <= 1),
  status text not null default 'draft' check (status in ('draft','approved','rejected')),
  source text not null default 'offline_analyzer',
  analyzer_version text,
  approved_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (anime_id, episode_number, event_key)
);

create index if not exists episode_events_runtime_idx
  on public.episode_events (anime_id, episode_number, status, at_ms);

create table if not exists public.user_episode_events (
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id uuid not null references public.episode_events(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  unlock_position_ms integer not null default 0,
  primary key (user_id, event_id)
);

create index if not exists user_episode_events_recent_idx
  on public.user_episode_events (user_id, unlocked_at desc);

create table if not exists public.episode_event_jobs (
  id bigint generated by default as identity primary key,
  anime_id bigint not null,
  episode_number integer not null check (episode_number > 0),
  status text not null default 'queued' check (status in ('queued','running','review','done','failed')),
  analyzer_version text,
  source_hash text,
  attempt_count integer not null default 0,
  last_error text,
  locked_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (anime_id, episode_number)
);

alter table public.episode_events enable row level security;
alter table public.user_episode_events enable row level security;
alter table public.episode_event_jobs enable row level security;

-- Runtime access goes through server routes with the service role.
-- Keep direct client writes closed; a compromised browser must not mint story unlocks.
drop policy if exists "episode_events_public_read" on public.episode_events;
drop policy if exists "user_episode_events_self_read" on public.user_episode_events;
create policy "user_episode_events_self_read"
  on public.user_episode_events
  for select
  using (auth.uid() = user_id);

comment on table public.episode_events is
  'Offline-analyzed, human/validator-approved episode story events used by AnimeBox Journey.';
comment on table public.user_episode_events is
  'Idempotent per-user Journey unlocks. Unlock is verified against server-trusted watched ranges.';
comment on table public.episode_event_jobs is
  'Queue/state for offline episode analysis. No LLM inference runs in the player runtime.';
