-- AnimeBox Profile Progression v1
-- Event-driven XP, Premium boost, richer achievements, and read-only profile progression.

alter table public.achievements
  drop constraint if exists achievements_metric_check;

alter table public.achievements
  add column if not exists category text not null default 'watch',
  add column if not exists rarity text not null default 'common',
  add column if not exists xp_reward integer not null default 25,
  add column if not exists hidden boolean not null default false,
  add column if not exists sort_order integer not null default 0;

alter table public.achievements
  add constraint achievements_metric_check
  check (metric = any (array[
    'episodes'::text,'titles'::text,'watch_minutes'::text,'comments'::text,
    'shonen_titles'::text,'romance_titles'::text,'action_titles'::text,
    'fantasy_titles'::text,'comedy_titles'::text
  ]));

alter table public.achievements drop constraint if exists achievements_rarity_check;
alter table public.achievements
  add constraint achievements_rarity_check
  check (rarity = any (array[
    'common'::text,'uncommon'::text,'rare'::text,'epic'::text,'legendary'::text
  ]));

alter table public.achievements drop constraint if exists achievements_xp_reward_check;
alter table public.achievements
  add constraint achievements_xp_reward_check
  check (xp_reward >= 0 and xp_reward <= 5000);

create index if not exists achievements_metric_threshold_idx
  on public.achievements(metric, threshold);

create table if not exists public.user_progression (
  user_id uuid primary key references auth.users(id) on delete cascade,
  total_xp bigint not null default 0,
  activity_xp bigint not null default 0,
  premium_bonus_xp bigint not null default 0,
  achievement_xp bigint not null default 0,
  credited_episodes bigint not null default 0,
  credited_titles bigint not null default 0,
  credited_watch_buckets bigint not null default 0,
  credited_comments bigint not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.user_progression enable row level security;
revoke all on table public.user_progression from anon, authenticated;
grant select, insert, update, delete on table public.user_progression to service_role;

create table if not exists public.progression_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  reason text,
  base_xp integer not null default 0,
  premium_bonus_xp integer not null default 0,
  achievement_xp integer not null default 0,
  total_xp integer not null default 0,
  created_at timestamptz not null default now(),
  unique(user_id, event_key)
);

alter table public.progression_events enable row level security;
revoke all on table public.progression_events from anon, authenticated;
grant select, insert, update, delete on table public.progression_events to service_role;

create index if not exists progression_events_user_created_idx
  on public.progression_events(user_id, created_at desc);

insert into public.achievements
(code,title,description,metric,threshold,icon,category,rarity,xp_reward,hidden,sort_order)
values
('first_episode','Первый шаг','Посмотри первую подтверждённую серию','episodes',1,'/brand/achievements/first-episode.svg','watch','common',25,false,10),
('episodes_10','Втянулся','Посмотри 10 подтверждённых серий','episodes',10,'/brand/achievements/episodes-stack.svg','watch','common',25,false,20),
('episodes_50','Выходные закончились','Посмотри 50 подтверждённых серий','episodes',50,'/brand/achievements/episodes-stack.svg','watch','uncommon',50,false,30),
('episodes_100','Марафонец','Посмотри 100 подтверждённых серий','episodes',100,'/brand/achievements/marathon.svg','watch','rare',100,false,40),
('episodes_250','Это уже образ жизни','Посмотри 250 подтверждённых серий','episodes',250,'/brand/achievements/marathon.svg','watch','rare',100,false,50),
('episodes_500','500 серий спустя','Посмотри 500 подтверждённых серий','episodes',500,'/brand/achievements/marathon.svg','watch','epic',250,false,60),
('episodes_1000','Ты ещё здесь?','Посмотри 1000 подтверждённых серий','episodes',1000,'/brand/achievements/marathon.svg','watch','legendary',500,false,70),
('first_completed','Финальные титры','Полностью заверши первое аниме','titles',1,'/brand/achievements/first-completed.svg','collection','common',25,false,110),
('titles_5','Начало коллекции','Полностью заверши 5 тайтлов','titles',5,'/brand/achievements/anime-collector.svg','collection','uncommon',50,false,120),
('titles_10','Коллекционер','Полностью заверши 10 тайтлов','titles',10,'/brand/achievements/anime-collector.svg','collection','rare',100,false,130),
('titles_25','Архивариус','Полностью заверши 25 тайтлов','titles',25,'/brand/achievements/anime-collector.svg','collection','rare',100,false,140),
('titles_50','Ветеран коллекции','Полностью заверши 50 тайтлов','titles',50,'/brand/achievements/anime-collector.svg','collection','epic',250,false,150),
('titles_100','Живая энциклопедия','Полностью заверши 100 тайтлов','titles',100,'/brand/achievements/anime-collector.svg','collection','legendary',500,false,160),
('watch_300','Вечер с AnimeBox','Набери 5 часов подтверждённого просмотра','watch_minutes',300,'/brand/achievements/marathon.svg','time','common',25,false,210),
('watch_600','Ещё одну серию','Набери 10 часов подтверждённого просмотра','watch_minutes',600,'/brand/achievements/marathon.svg','time','uncommon',50,false,220),
('watch_1500','Марафон','Набери 25 часов подтверждённого просмотра','watch_minutes',1500,'/brand/achievements/marathon.svg','time','rare',100,false,230),
('watch_3000','Не спал, но доволен','Набери 50 часов подтверждённого просмотра','watch_minutes',3000,'/brand/achievements/marathon.svg','time','rare',100,false,240),
('watch_6000','Ветеран экрана','Набери 100 часов подтверждённого просмотра','watch_minutes',6000,'/brand/achievements/marathon.svg','time','epic',250,false,250),
('watch_15000','Другой мир','Набери 250 часов подтверждённого просмотра','watch_minutes',15000,'/brand/achievements/marathon.svg','time','legendary',500,false,260),
('first_comment','Есть что сказать','Оставь первый комментарий','comments',1,'/brand/achievements/comments.svg','community','common',25,false,310),
('comments_10','Разговор начался','Оставь 10 комментариев','comments',10,'/brand/achievements/comments.svg','community','uncommon',50,false,320),
('comments_50','Завсегдатай','Оставь 50 комментариев','comments',50,'/brand/achievements/comments.svg','community','rare',100,false,330),
('shonen_10','Путь героя','Заверши 10 тайтлов Сёнен','shonen_titles',10,'/brand/achievements/anime-collector.svg','genres','rare',100,false,410),
('romance_10','Разбитое сердце','Заверши 10 романтических тайтлов','romance_titles',10,'/brand/achievements/anime-collector.svg','genres','rare',100,false,420),
('action_10','Адреналин','Заверши 10 экшен-тайтлов','action_titles',10,'/brand/achievements/anime-collector.svg','genres','rare',100,false,430),
('fantasy_10','За гранью','Заверши 10 фэнтези-тайтлов','fantasy_titles',10,'/brand/achievements/anime-collector.svg','genres','rare',100,false,440),
('comedy_10','Смехотерапия','Заверши 10 комедийных тайтлов','comedy_titles',10,'/brand/achievements/anime-collector.svg','genres','rare',100,false,450)
on conflict (code) do update set
  title=excluded.title,
  description=excluded.description,
  metric=excluded.metric,
  threshold=excluded.threshold,
  icon=excluded.icon,
  category=excluded.category,
  rarity=excluded.rarity,
  xp_reward=excluded.xp_reward,
  hidden=excluded.hidden,
  sort_order=excluded.sort_order;

CREATE OR REPLACE FUNCTION public.community_metrics(p_user uuid)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  with completed_episode_rows as (
    select e.anime_id, e.episode_number
    from animebox_watch.progress p
    join animebox_watch.episodes e on e.id = p.episode_id
    where p.user_id = p_user and p.completed_at is not null
  ),
  completed_titles as (
    select a.id, a.genres
    from public.anime_catalog a
    join completed_episode_rows h on h.anime_id = a.id
    where a.finished and a.total_episodes is not null
      and h.episode_number <= a.total_episodes
    group by a.id, a.genres, a.total_episodes
    having count(distinct h.episode_number) >= a.total_episodes
  ),
  watch_totals as (
    select
      count(*) filter (where p.completed_at is not null)::bigint as completed_episodes,
      coalesce(sum(p.active_ms), 0)::bigint as active_ms
    from animebox_watch.progress p
    where p.user_id = p_user
  )
  select jsonb_build_object(
    'episodes',(select completed_episodes from watch_totals),
    'titles',(select count(*) from completed_titles),
    'minutes',(select floor(active_ms / 60000.0)::bigint from watch_totals),
    'watch_minutes',(select floor(active_ms / 60000.0)::bigint from watch_totals),
    'active_ms',(select active_ms from watch_totals),
    'shonen_titles',(select count(*) from completed_titles where genres && array['Shounen','Shonen','Сёнен','Сенен']),
    'romance_titles',(select count(*) from completed_titles where genres && array['Romance','Романтика']),
    'action_titles',(select count(*) from completed_titles where genres && array['Action','Экшен']),
    'fantasy_titles',(select count(*) from completed_titles where genres && array['Fantasy','Фэнтези']),
    'comedy_titles',(select count(*) from completed_titles where genres && array['Comedy','Комедия']),
    'comments',(select count(*) from public.comments where user_id=p_user and deleted_at is null),
    'watching',(select count(*) from public.anime_library where user_id=p_user and status='watching'),
    'planned',(select count(*) from public.anime_library where user_id=p_user and status='planned'),
    'completed',(select count(*) from public.anime_library where user_id=p_user and status='completed'),
    'dropped',(select count(*) from public.anime_library where user_id=p_user and status='dropped')
  );
$function$;

CREATE OR REPLACE FUNCTION public.sync_user_progression(p_user uuid, p_premium_boost boolean, p_event_key text, p_reason text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  metrics jsonb;
  current_row public.user_progression%rowtype;
  target_episodes bigint; target_titles bigint; target_watch_buckets bigint; target_comments bigint;
  delta_episodes bigint; delta_titles bigint; delta_watch_buckets bigint; delta_comments bigint;
  activity_gain bigint := 0; premium_gain bigint := 0; achievement_gain bigint := 0;
  unlocked jsonb := '[]'::jsonb; result jsonb;
begin
  if p_user is null then raise exception 'INVALID_USER'; end if;
  if p_event_key is null or length(trim(p_event_key))=0 or length(p_event_key)>180 then
    raise exception 'INVALID_EVENT_KEY';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user::text,417));
  metrics := public.community_metrics(p_user);

  insert into public.user_progression(user_id) values(p_user)
  on conflict(user_id) do nothing;

  select * into current_row
  from public.user_progression
  where user_id=p_user
  for update;

  target_episodes := greatest(0,coalesce((metrics->>'episodes')::bigint,0));
  target_titles := greatest(0,coalesce((metrics->>'titles')::bigint,0));
  target_watch_buckets := greatest(0,floor(coalesce((metrics->>'active_ms')::numeric,0)/1800000.0)::bigint);
  target_comments := least(50,greatest(0,coalesce((metrics->>'comments')::bigint,0)));

  delta_episodes := greatest(0,target_episodes-current_row.credited_episodes);
  delta_titles := greatest(0,target_titles-current_row.credited_titles);
  delta_watch_buckets := greatest(0,target_watch_buckets-current_row.credited_watch_buckets);
  delta_comments := greatest(0,target_comments-current_row.credited_comments);

  activity_gain := delta_episodes*10 + delta_titles*75 + delta_watch_buckets*15 + delta_comments*2;
  if coalesce(p_premium_boost,false) and activity_gain>0 then
    premium_gain := floor(activity_gain*0.20)::bigint;
  end if;

  with eligible as (
    select a.code from public.achievements a
    where not a.hidden and coalesce((metrics->>a.metric)::bigint,0)>=a.threshold
  ),
  inserted as (
    insert into public.user_achievements(user_id,achievement_code)
    select p_user,e.code from eligible e
    on conflict do nothing
    returning achievement_code
  )
  select
    coalesce(sum(a.xp_reward),0)::bigint,
    coalesce(jsonb_agg(jsonb_build_object(
      'code',a.code,'title',a.title,'rarity',a.rarity,'xpReward',a.xp_reward
    ) order by a.sort_order,a.code),'[]'::jsonb)
  into achievement_gain,unlocked
  from inserted i join public.achievements a on a.code=i.achievement_code;

  update public.user_progression set
    activity_xp=activity_xp+activity_gain,
    premium_bonus_xp=premium_bonus_xp+premium_gain,
    achievement_xp=achievement_xp+achievement_gain,
    total_xp=total_xp+activity_gain+premium_gain+achievement_gain,
    credited_episodes=greatest(credited_episodes,target_episodes),
    credited_titles=greatest(credited_titles,target_titles),
    credited_watch_buckets=greatest(credited_watch_buckets,target_watch_buckets),
    credited_comments=greatest(credited_comments,target_comments),
    updated_at=now()
  where user_id=p_user;

  if activity_gain+premium_gain+achievement_gain>0 then
    insert into public.progression_events(
      user_id,event_key,reason,base_xp,premium_bonus_xp,achievement_xp,total_xp
    ) values (
      p_user,p_event_key,left(p_reason,120),
      activity_gain::integer,premium_gain::integer,achievement_gain::integer,
      (activity_gain+premium_gain+achievement_gain)::integer
    )
    on conflict(user_id,event_key) do nothing;
  end if;

  select jsonb_build_object(
    'total_xp',total_xp,'activity_xp',activity_xp,
    'premium_bonus_xp',premium_bonus_xp,'achievement_xp',achievement_xp,
    'credited_episodes',credited_episodes,'credited_titles',credited_titles,
    'credited_watch_buckets',credited_watch_buckets,'credited_comments',credited_comments,
    'earned_now',activity_gain+premium_gain+achievement_gain,
    'premium_bonus_now',premium_gain,'unlocked',unlocked,'updated_at',updated_at
  )
  into result from public.user_progression where user_id=p_user;

  return result;
end;
$function$;

CREATE OR REPLACE FUNCTION public.award_achievements(p_user uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  perform public.sync_user_progression(
    p_user,false,
    'legacy-award:' || floor(extract(epoch from clock_timestamp())*1000)::bigint::text,
    'legacy'
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.my_community_profile()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare uid uuid:=auth.uid(); result jsonb;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  select jsonb_build_object(
    'stats',public.community_metrics(uid),
    'progression',coalesce(
      (select jsonb_build_object(
        'total_xp',p.total_xp,'activity_xp',p.activity_xp,
        'premium_bonus_xp',p.premium_bonus_xp,'achievement_xp',p.achievement_xp,
        'updated_at',p.updated_at
      ) from public.user_progression p where p.user_id=uid),
      jsonb_build_object(
        'total_xp',0,'activity_xp',0,'premium_bonus_xp',0,'achievement_xp',0,'updated_at',null
      )
    ),
    'achievements',(
      select coalesce(jsonb_agg(
        to_jsonb(a)||jsonb_build_object('earned_at',u.earned_at)
        order by a.sort_order,a.code
      ),'[]'::jsonb)
      from public.achievements a
      left join public.user_achievements u
        on u.achievement_code=a.code and u.user_id=uid
      where not a.hidden or u.earned_at is not null
    ),
    'library',(
      select coalesce(jsonb_agg(jsonb_build_object(
        'anime_id',l.anime_id,'title',a.title,'status',l.status
      ) order by l.updated_at desc),'[]'::jsonb)
      from public.anime_library l
      join public.anime_catalog a on a.id=l.anime_id
      where l.user_id=uid
    )
  ) into result;
  return result;
end;
$function$;


revoke execute on function public.sync_user_progression(uuid, boolean, text, text)
from public, anon, authenticated;
grant execute on function public.sync_user_progression(uuid, boolean, text, text)
to service_role;

revoke execute on function public.award_achievements(uuid)
from public, anon, authenticated;
grant execute on function public.award_achievements(uuid)
to service_role;

revoke execute on function public.my_community_profile()
from public, anon;
grant execute on function public.my_community_profile()
to authenticated, service_role;

do $block$
declare uid uuid;
begin
  for uid in select id from public.profiles loop
    perform public.sync_user_progression(
      uid,
      false,
      'migration:profile-progression-v1',
      'backfill'
    );
  end loop;
end;
$block$;
